### ISSUE TITLE
Migrate to httr2

### ISSUE THREAD

**Issue by AliSajid** [CogDisResLab/drugfindR#22]
Related Issues:

1. [ropensci/webmockr#122](https://github.com/ropensci/webmockr/issues/122)
2. [ropensci/vcr#237](https://github.com/ropensci/vcr/issues/237)

Since [httr](https://github.com/r-lib/httr) has been deprecated, it would be a good idea to migrate to [httr2](https://github.com/r-lib/httr2) for compliance.

A blocker right now is that we rely on `vcr` and `webmockr` for some of our tests. Once the above issues are resolved we should move to `httr2`.

**Comment by sckott** [comment]
Sorry about the hold up on `httr2` integration - I can't promise a date when it will be done, but I'm hoping to get back to it soon

**Comment by sckott** [comment]
Both `vcr` and `webmockr` now support `httr2` with the latest versions of each pkg on cran. Let me know if you run into any issues

**Comment by AliSajid** [comment]
@sckott Woohoo! Thank you for all the work! I'll be running tests on this soon. This made my day. :)

**Comment by sckott** [comment]
great!
